Task 2
N25443/okui_20230403 pull request #2
Opened 2023-04-19 06:46 UTC by N25443

## 詳細

- テーブルの本実装
1.  テーブルの本実装
2.  曜日によって行の色を変更（オプション）

- フォームの充実
 3. フォームの上にプルダウンを追加
 4. 追加ボタン押下時に値がテーブルの選択した日付の食費/固定費に反映される 
 5. Tableの日付を押下時にFormに切り替わり、 かつ押下した日付がプルダウンで選択された状態で表示されるようにする（オプション）

## 画面キャプチャ
テーブルの本実装
曜日によって行の色を変更（オプション）
![image](https://user-images.githubusercontent.com/118702462/232970729-72d71ff6-cb24-4909-a2d4-47bf8d7d8d84.png)
![image](https://user-images.githubusercontent.com/118702462/232970805-3534c570-7a12-4839-9f76-4cb9a9b6e3dc.png)
フォームの上にプルダウンを追加
追加ボタン押下時に値がテーブルの選択した日付の食費/固定費に反映される
![image](https://user-images.githubusercontent.com/118702462/232970871-c26d4aed-6d97-4337-9e9c-40fe6da4fc6d.png)
![image](https://user-images.githubusercontent.com/118702462/232970913-c16ec456-cebe-4a19-bc75-84bc98deb73e.png)
![image](https://user-images.githubusercontent.com/118702462/232970994-d5fd975c-781a-4b2f-8ad4-ae0a8b73ae7e.png)
![image](https://user-images.githubusercontent.com/118702462/232988152-077d6700-60d0-4cd1-9b4e-d84dab75783d.png)
 Tableの日付を押下時にFormに切り替わり、 かつ押下した日付がプルダウンで選択された状態で表示されるようにする（オプション）<br>
＜ 4月10日を押下した場合＞
![image](https://user-images.githubusercontent.com/118702462/232989066-0e5757bf-b038-47c6-b9e8-7420cdafd760.png)

2023-04-19 08:24 UTC, ysakajo requested changes

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +      const cost: Ref<number> = ref(0);
型指定を意識できていて素晴らしいです！

直す必要はないですが、下記のような記載でも型指定できることは覚えておいてください！
Web上でも下記の記載の方が一般的そうでした。
`const cost= ref<number>(0);`

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +        }
修正する必要はないですが、頭の片隅に置いておいてほしい内容を補足しておきます。
（20日の朝会でも共有します！）

# 考え方
一つの関数に対しては可能な限り小さな役割を持たせるように設計してほしいです。
今の関数ではfixedCost, foodCostという二つの変数に対する更新をすることになっていて、内部で更新先を切り替えているけれど、このままだと今後更新先が増えた場合、さらに複雑な関数になることが予想されます。

例えば交通費が増えることを考えた場合、この関数には
条件分岐（else if）が増えてさらに複雑な関数になってしまいます。
さらに項目が増えるとelse if がどんどん増えていってしまうことになり、
関数の責任がどんどん増大していってしまいます。

このような複雑な条件式を持つ関数は好ましくないです。
なぜならば、このコードを読む人は実務においては他人であることがほとんどで、
初見の人が条件分岐の多いコードを読むことは大変だからです。

ですので、なるべく小さな関数を作って、その関数を結合していくといったイメージで関数は設計したほうが良いコードになりやすいです。

# ここでの修正案
ここでは条件式ではなく、objectの配列として定義したほうが分岐が少なくなり、わかりやすいコードになるかと思います。

具体的な修正案としては、

```
const costUpdaters= [{
    target:1,
    updater: (newCost)  => cost1.value=newCost
},
{
    target:2,
    updater: (newCost)  => cost2.value=newCost
},
{
    target:3,
    updater: (newCost)  => cost3.value=newCost
}
]

const setCost = (newCost,targetCost) => costUpdaters.filter(elm => elm.target === targetCost).updater()
```

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +          props.onTabButtonClick('Table.vue');
` props.onTabButtonClick('Table.vue');`
上記の処理は条件にかかわらず実施されるので、ifの外側に出しておきましょう！

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +      />
文字列を入力すると、そのまま文字列がテーブルに反映されてしまうようになっています！
数値だけ反映されるようにしてみてください！

2023-04-19 08:24 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +    setup(props) {
HouseholdMainではpropsを使用していないので、setupの引数に入れる必要はないです！
またreturnする必要もないです！

2023-04-19 08:24 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +        onTabButtonClick('Form.vue');
タブボタンをクリックしたときだけでなく、ほかの箇所でも使うようになったので関数名が不適切になっています！
何をするのかを表す関数名にすると、参照先の内容を見にいかなくて済むようになるので、関数名を変更しましょうか！

Form.vueも同様

2023-04-19 08:24 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +        { date: 1, day: '土', foodCost: null, fixedCost: null },
30日分のオブジェクトを直接書いていますが、
もっと簡単に記載する方法を考えてみましょう！

for文でも実装可能ですが、記載がシンプルになるので、
練習の意味も込めて、スプレッド構文とmap関数を使ってみてください。
（ここは調べてみて検討がつかなければ、相談してください）

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +      <option value="2">固定費</option>
優先度は低いので、時間次第で対応有無は判断しましょう。

ここで定義されている、1：食費、2：固定費を合わせて定数化するほうが望ましいです。

今だと複数個所でべた書きされていますが、
情報が１か所に固待っていることによって、後々コード理解をしやすくなります。
また、例えば交際費など管理する項目を追加したいとなった場合も、
その定数だけを変更すればよくなるので、拡張性が高まります。
（凝集度が高いと言ったりします。）

2023-04-19 08:24 UTC, ysakajo commented on src/components/Form.vue
> +      const dateList = ref(dateListInit);
日付の選択肢の配列としてしか使っていないのであれば、
リアクティブにする必要はなさそうですが、何か意図がありますか？

このあたりの日付一覧を定義している部分についてはどう考えて実装したか聞かせてもらいたいです！

2023-04-19 08:24 UTC, ysakajo commented on src/components/Table.vue
> +        }
オプションなので対応するかは時間次第ですが、下記確認お願いします。

この書き方だと内容を理解するのにif分をすべて読む必要があり、
理解に時間がかかってしまいます。
また、ほかの曜日も色を変更したいとなったときにはif文を
その分だけ記載する必要があります。

なので、
曜日の一覧を定義し、そこに色も併せて定義しておく方が望ましいです。
こうすることで、定数を見れば大体どのようなことをしたいかわかり、
変更の際にもこの定数のみ変更すればよくなります。

例
```
const DAY_OF_WEEKS：DayOfWeek[] = [
  {
    id:1,
    name: '月',
    color: 'bg-gray-100', // こう書けば、tailwindを使用できる
  },
 ・・・
]
```

2023-04-19 08:24 UTC, ysakajo commented on src/components/Table.vue
> +      const tableClass: string[] = props.houseHolds.map(function (houseHold) {
このままでももちろんまちがいではないですが、
モダンな記載に慣れるために、mapの中をアロー関数で記載してみましょうか。

2023-04-19 08:33 UTC, N25443 commented on src/components/Form.vue
> +          props.onTabButtonClick('Table.vue');
指摘点について修正しました。

2023-04-19 08:45 UTC, N25443 commented on src/components/Form.vue
> +      />
指摘点について対応しました。

2023-04-19 08:45 UTC, N25443 commented on src/components/HouseholdMain.vue
> +    setup(props) {
指摘点について対応しました。

2023-04-19 08:53 UTC, N25443 commented on src/components/Table.vue
> +      const tableClass: string[] = props.houseHolds.map(function (houseHold) {
指摘点について対応しました。

2023-04-19 08:59 UTC, N25443 commented on src/components/Form.vue
> +      const dateList = ref(dateListInit);
参考にしたサイトのまま記載してしまっていました。
リアクティブにする必要はないのでdateListを配列としてリファクタリングし、dateListInitを削除しました。

2023-04-20 05:43 UTC, N25443 commented on src/components/HouseholdMain.vue
> +        { date: 1, day: '土', foodCost: null, fixedCost: null },
指摘点について対応しました。

2023-04-20 06:03 UTC, N25443 commented on src/components/Table.vue
> +        }
指摘点について対応しました。

2023-04-20 06:20 UTC, N25443 commented on src/components/HouseholdMain.vue
> +        onTabButtonClick('Form.vue');
指摘点について対応しました。

2023-04-20 06:44 UTC, N25443 commented on src/components/Form.vue
> +      <option value="2">固定費</option>
こちらの指摘については時間の関係上、このままでいかせていただこうと思います。

2023-04-20 07:09 UTC, ysakajo commented on src/components/HouseholdMain.vue
> +        onTabButtonClick('Form.vue');
対応されていないように見えます！
pushもれ？

2023-04-20 07:17 UTC, ysakajo commented on src/components/Table.vue
> +        }
定数は定義されていますが、
定数に設定したcolorをこの関数で使用できていないです！

せっかくなので、使用するように変更してみてください！
複数コンポーネントで定数を使用することになると思うので、これもファイルを分けちゃいましょう！

2023-04-20 08:22 UTC, N25443 commented on src/components/Table.vue
> +        }
指摘点について対応しました。

2023-04-20 08:35 UTC, ysakajo commented on src/components/Table.vue
> +      },
DAY_OF_WEEKSはimportしたものを使っているので、これは不要だと思います！
不要なものは削除しちゃいましょう！

2023-04-20 08:47 UTC, merged